# .github/workflows/ci.yml
name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get repo name
        id: get_repo
        run: echo "REPO=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v3

      - name: Gradle Setup
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper

      - name: Gradle build
        run: ./gradlew build -x test excludePerformanceTest

      - name: Upload Build Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./build/libs/*.jar

      - name: Trigger CD
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUBACTION_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-cd
